<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds buttons for linking to recording systems, or shows existing link info.
 *
 * */
function recording_system_links_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'user_form') {
    $formUserId = $form_state->getFormObject()->getEntity()->id();
    if ($formUserId === \Drupal::currentUser()->id() && \Drupal::currentUser()->hasPermission('connect recording system links')) {
      $form['recording_system_links'] = [
        '#type' => 'details',
        '#open' => TRUE,
        '#title' => t('Recording system links'),
      ];
      $query = Drupal::database()->select('recording_system_config', 'rsc');
      $query->addJoin('LEFT OUTER', 'recording_system_oauth_tokens', 'rst', 'rst.recording_system_config_id=rsc.id AND rst.uid=' . \Drupal::currentUser()->id());
      $query->fields('rsc', ['title', 'machine_name', 'description']);
      $query->addField('rst', 'uid', 'rst_uid');
      $links = $query->orderBy('title')->execute();
      foreach ($links as $link) {
        if ($link->rst_id) {
          // Existing link.
          $form['recording_system_links'][$link->machine_name] = [
            '#type' => 'item',
            '#title' => t('Your account is linked to to %title', ['%title' => $link->title]),
            '#description' => $link->description,
          ];
        }
        else {
          // New link button with info.
          $form['recording_system_links'][$link->machine_name] = [
            '#type' => 'details',
            '#open' => TRUE,
            '#title' => $link->title,
            '#description' => $link->description,
          ];
        }
        $form['recording_system_links'][$link->machine_name]['connect_recording_system'] = [
          '#type' => 'link',
          '#title' => t('Connect to %title', ['%title' => $link->title]),
          '#url' => Url::fromRoute('recording_system_links.connect', ['machineName' => $link->machine_name]),
          '#attributes' => [
            'class' => ['button'],
          ],
        ];
      }
    }

    // @todo Add information list of existing connections
  }
}